services:
  sd:
    image: ghcr.io/cmdr2/stable-diffusion-webui-docker:master
    container_name: stable-diffusion
    ports:
      - "7860:7860"
    volumes:
      - sd-data:/data
    environment:
      - CLI_ARGS=--medvram
    restart: unless-stopped

volumes:
  sd-data:
